home:
  pattern:    ~^/$~i
  controller: StatsApp\Controller\DefaultController
  method:     indexAction

stats.get:
  pattern:    ~^/stats$~i
  controller: StatsApp\Controller\DefaultController
  method:     homeAction

stats.post:
  pattern:    ~^/stats/save$~i
  controller: StatsApp\Controller\DefaultController
  method:     saveAction

login.page:
  pattern:    ~^/login$~i
  controller: ShopApp\Controller\DefaultController
  method:     loginAction

logout.page:
  pattern:    ~^/logout$~i
  controller: ShopApp\Controller\DefaultController
  method:     logoutAction

profile.page:
  pattern:    ~^/profile$~i
  controller: ShopApp\Controller\DefaultController
  method:     profileAction

catalog.page:
  pattern:    ~^/catalog$~i
  controller: ShopApp\Controller\DefaultController
  method:     catalogAction

cart.page:
  pattern:    ~^/cart$~i
  controller: ShopApp\Controller\DefaultController
  method:     cartAction